The ''Base Geometry'' module
======================

Using ''BaseGeometry''
-------------------

Class
    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

    >>> bg = BaseGeometry()

Area
    >>> bg.area()
    Traceback (most recent call last):
        ...
    Exception: area() is not implemented

    >>> bg.integer_validator("my_int", 12)
    >>> bg.integer_validator("width", 89)

0
    >>> bg.integer_validator("age", 0)
    Traceback (most recent call last):
        ...
    ValueError: age must be greater than 0

Negative
    >>> bg.integer_validator("distance", -4)
    Traceback (most recent call last):
        ...
    ValueError: distance must be greater than 0

Positive
    >>> bg.integer_validator("name", 3)

Float
    >>> bg.integer_validator("age", 1.5)
    Traceback (most recent call last):
        ...
    TypeError: age must be an integer

String
    >>> bg.integer_validator("name", "John")
    Traceback (most recent call last):
        ...
    TypeError: name must be an integer

List
    >>> bg.integer_validator("name", [1])
    Traceback (most recent call last):
        ...
    TypeError: name must be an integer

Tuple
    >>> bg.integer_validator("name", (1, ))
    Traceback (most recent call last):
        ...
    TypeError: name must be an integer

None
    >>> bg.integer_validator("name", None)
    Traceback (most recent call last):
        ...
    TypeError: name must be an integer

Empty
    >>> bg.integer_validator()
    Traceback (most recent call last):
        ...
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

1 argument
    >>> bg.integer_validator("name")
    Traceback (most recent call last):
        ...
    TypeError: integer_validator() missing 1 required positional argument: 'value'

3 arguments
    >>> bg.integer_validator("name", 1, 2)
    Traceback (most recent call last):
        ...
    TypeError: integer_validator() takes 3 positional arguments but 4 were given

1 area arg
    >>> bg.area(2)
    Traceback (most recent call last):
        ...
    TypeError: area() takes 1 positional argument but 2 were given

2 area arg
    >>> bg.area(2, 1)
    Traceback (most recent call last):
        ...
    TypeError: area() takes 1 positional argument but 3 were given
